"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""


def fib_gen():

    fib_arr = [1, 1]
    tmp = 0
    i = 1
    # for i in range(1, 400):
    while tmp < 4000000:
        tmp = fib_arr[i] + fib_arr[i - 1]
        fib_arr.append(tmp)
        i += 1

    sum_seq = 0

    # sum of even fibonacci sequence
    for x in fib_arr:
        if x % 2 == 0:
            sum_seq += x

    return fib_arr, sum_seq


fib_seq, sum_even = fib_gen()
print("Even Fibonacci no whose values not exceeding 4M\n >>", fib_seq)
print("Sum of Even Fibonacci Sequence is", sum_even)
